AWSTemplateFormatVersion: '2010-09-09'
Description: 'WordPress Instance using AWS CloudFormation and Serverless Technology'

Parameters:
  
  DBUsername:
    NoEcho: 'true'
    Description: The WordPress database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
    Default: 'admin'
    
  DBPassword:
    NoEcho: 'true'
    Description: MySQL root password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
    Default: 'SimpliLearn12345'
  
  DBPort:
    Type: Number
    Description: 'Database port to make connections.'
    Default: 3306

  DBAccessSourceIP:
    Type: String
    Description: 'Your IP address to access the database (e.g., xx.xx.xx.xx/32)'
    Default: '0.0.0.0/0'

  EC2InstanceImageId:
    Type: AWS::EC2::Image::Id
    Description: 'ID of the AMI for the EC2 instances'
    Default: ami-053b0d53c279acc90
  
Resources:

  # RDS Database Instance
  WordPressDatabase:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: 'WordPressDB'
      AllocatedStorage: 20
      Engine: 'mysql'
      EngineVersion: '8.0.32'                      # Use the desired MySQL version
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      MultiAZ: false                            # Enable/Disable Multi-AZ deployment for high availability
      StorageType: 'gp2'
      DBInstanceClass: 'db.t2.micro'            # Replace with the desired instance type
      
  # AWS Secrets Manager to store database credentials
  WordPressDatabaseSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: 'WordPressDBSecret'
      Description: 'Secret for the WordPress database credentials'
      SecretString:
        Fn::Join:
          - ''
          - - '{"username":"'
            - !Ref DBUsername
            - '","password":"'
            - !Ref DBPassword
            - '","engine":"mysql","host":"'
            - !GetAtt WordPressDatabase.Endpoint.Address
            - '","port":"'
            - !Ref DBPort
            - '","dbname":"wordpress"}'

  # Security Group
  WordPressInstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security Group for WordPress Ec2 Instances'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref DBAccessSourceIP
      Tags:
        - Key: 'Name'
          Value: 'WordPressDBSecurityGroup'

  # DEV EC2 Instance
  DevWordPressInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref EC2InstanceImageId
      InstanceType: 't2.micro'           # Replace with the desired instance type
      SecurityGroups:
        - !Ref WordPressInstanceSecurityGroup
      KeyName: 'simplilearn-keypair'      # Replace with your EC2 Key Pair name
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          sudo su
          apt update
          apt install -y apache2 mysql-server php libapache2-mod-php php-mysql

          systemctl enable apache2
          systemctl start apache2

          # Install AWS CLI to retrieve secrets from Secrets Manager
          apt install -y awscli

          # Get database credentials from Secrets Manager
          DB_SECRET=$(aws secretsmanager get-secret-value --secret-id WordPressDBSecret --query SecretString --output text)
          DB_HOST=$(echo "$DB_SECRET" | jq -r '.host')
          DB_USERNAME=$(echo "$DB_SECRET" | jq -r '.username')
          DB_PASSWORD=$(echo "$DB_SECRET" | jq -r '.password')
          DB_NAME=$(echo "$DB_SECRET" | jq -r '.dbname')

          # Download and install WordPress
          cd /var/www/html
          wget https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          mv wordpress/* .
          rm -rf wordpress latest.tar.gz

          # Configure WordPress
          cp wp-config-sample.php wp-config.php
          sed -i "s/database_name_here/${DB_NAME}/g" wp-config.php
          sed -i "s/username_here/${DB_USERNAME}/g" wp-config.php
          sed -i "s/password_here/${DB_PASSWORD}/g" wp-config.php
          sed -i "s/localhost/${DB_HOST}/g" wp-config.php
          chown -R www-data:www-data /var/www/html

          # Restart Apache
          systemctl restart apache2


Outputs:
  WordPressDBHostname:
    Description: 'Hostname of the RDS WordPress database.'
    Value: !GetAtt WordPressDatabase.Endpoint.Address